name: Solar System Workflow

on: 
  workflow_dispatch: 
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

permissions:
    id-token: write
    contents: read

    
jobs:
  
  dev-deploy:

       runs-on: ubuntu-latest
       steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Login to Azure
          run: |
            az login --username "odl_user_1225434@cloudlabs4kodeKloud.onmicrosoft.com" --password "bnnr78TUT*v9"
            az account set --subscription "269af900-c1d0-4f05-abf3-fb53e68a44f8"
    
        
        - name: Get AKS Credentials
          run: az aks get-credentials --resource-group ODL-azure-1225434 --name AKS-1kodekloudapp
        
        - name: List Azure Subscriptions
          run: | 
            kubectl apply -n ${{ vars.NAMESPACE }} -f kubernetes/development/ingress-controller.yaml
            

    
        - name: INGRESS IP 
          run: |
            INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            echo "INGRESS_IP=${INGRESS_IP}" >> $GITHUB_ENV
            

        - name: Replace tokens in a manifest file
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: '["kubernetes/development/*.yaml"]'
          env:
            CDN: 
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{vars.REPLICAS}}
            IMAGE: ${{ vars.DOCKER_USERNAME}}/solar.system:${{github.sha}}
            INGRESS_IP: ${{ env.INGRESS_IP }}

        - name: Check files
          run:
            cat kubernetes/development/*.yaml

          




