name: Solar System Workflow

on: 
  workflow_dispatch: 
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

permissions:
    id-token: write
    contents: read

    
jobs:
  
  dev-deploy:

       runs-on: ubuntu-latest
       steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Login to Azure
          run: |
            az login --username "odl_user_1225434@cloudlabs4kodeKloud.onmicrosoft.com" --password "bnnr78TUT*v9"
    
        - name: List Azure Subscriptions
          run: az account list

          




