name: Solar System Workflow

on: 
  workflow_dispatch: 
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:

  dev-deploy:
      
       runs-on: ubuntu-latest
       steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Azure CLI
          uses: azure/CLI@v1
          with:
            azcliversion: latest
            inlineScript: |
              az login
              az login --service-principal -u odl_user_1225434@cloudlabs4kodeKloud.onmicrosoft.com -p bnnr78TUT*v9 --tenant d5cb8a33-eea4-444a-9177-3c24547f595d



          




